# Generated by Django 3.0.8 on 2020-08-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_pledge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='projecy',
            new_name='project',
        ),
    ]
